# Generated by Django 3.2.8 on 2021-10-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(help_text='접속한 페이지', max_length=50)),
                ('ip', models.CharField(blank=True, max_length=30, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=200, null=True)),
                ('accessed_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
